Repository premAI-io/state-of-open-source-ai, pull requests merged in 2023-10, with the labels that each got.

#66 docs(readme): update readme to be more verbose
  README.md
Labels: framework & docs

#67 fix readme links
  .github/workflows/pages.yml
  CITATION.cff
  README.md
  index.md
  references.bib
  sdk.md
Labels: framework & docs

#68 pdf: a4paper
  .github/workflows/pages.yml
Labels: framework & docs

#69 CI: split build/check
  .github/workflows/pages.yml
  eval-datasets.md
  model-formats.md
Labels: framework & docs

#71 add issue template
  .github/ISSUE_TEMPLATE/content_request.yml
Labels: framework & docs

#73 disambiguate Local.AI
  desktop-apps.md
Labels: bug, content

#74 misc release fixes
  _config.yml
  _static/emails.js
  desktop-apps.md
  index.md
  mlops-engines.md
  models.md
  sdk.md
  unaligned-models.md
  vector-db.md
Labels: bug, framework & docs

#79 pdf: fix hyperref
  .github/workflows/pages.yml
  _config.yml
  index.md
  requirements.txt
Labels: bug, framework & docs

#80 emails: hide popup before setting cookies
  _static/emails.js
  sdk.md
Labels: bug, framework & docs

#82 fix comments
  .github/workflows/pages.yml
Labels: framework & docs

#84 Better email modal + pretendard font + fix link utf8 char
  _config.yml
  _static/emails.css
  _static/emails.js
  _static/external_target.css
  _static/font.css
  fine-tuning.md
  references.bib
  references.md
Labels: framework & docs

#86 build: use local_extensions
  .github/workflows/pages.yml
  _config.yml
  _static/download_pdf.js
  index.md
  prem_theme/__init__.py
  prem_theme/layout.html
  prem_theme/theme.conf
Labels: framework & docs

#85 Update README.md
  README.md
Labels: framework & docs

#87 theme: fix code font
  _static/font.css
Labels: framework & docs

#88 description: FOMO cure
  README.md
  index.md
Labels: content

#91 CI: fix build
  .github/workflows/pages.yml
Labels: bug, framework & docs

#92 add DOI, add PR & cron CI, update badges
  .github/workflows/pages.yml
  CITATION.cff
  _config.yml
  badges.py
  index.md
  references.bib
Labels: framework & docs

#97 models: note about open source vs licence
  _config.yml
  models.md
  references.md
Labels: content

#101 fix links
  desktop-apps.md
  eval-datasets.md
  models.md
  sdk.md
Labels: bug, content
