Repository premAI-io/state-of-open-source-ai, pull requests merged in 2023-11, with the labels that each got.

#98 mlops-engines: add LocalAI
  desktop-apps.md
  mlops-engines.md
  model-formats.md
  sdk.md
Labels: content

#115 fix links
  _config.yml
  index.md
  mlops-engines.md
  models.md
  references.md
  sdk.md
Labels: bug, content

#114 mailchimp emails
  _config.yml
  _static/emails.css
  _static/emails.js
Labels: framework & docs

#117 fix link
  models.md
Labels: bug, content

#118 fix links
  sdk.md
Labels: content
